#include "src/port/ShipInit.hpp"
#include "src/port/Rando/Logic/Logic.h"

using namespace Rando::Logic;

// clang-format off
static RegisterShipInitFunc initFunc([]() {
    Regions[RR_FREEZEEZY_PEAK_ENTRANCE] = RandoRegion{ .regionName = "Freezeezy Peak Entrance", .mapId = MAP_27_FP_FREEZEEZY_PEAK,
        .checks = {
            CHECK(RC_FP_JIGGY_JINJO,		    CAN_COLLECT_JINJOS(LEVEL_5_FREEZEEZY_PEAK)),
            CHECK(RC_FP_JIGGY_SLED_TO_BOGGY,    CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
            CHECK(RC_FP_NOTE_FIRST_SLOPE_1,	    true),
            CHECK(RC_FP_NOTE_FIRST_SLOPE_2,	    true),
            CHECK(RC_FP_NOTE_FIRST_SLOPE_3,	    true),
            CHECK(RC_FP_NOTE_FIRST_SLOPE_4,	    true),
            CHECK(RC_FP_NOTE_FIRST_SLOPE_5,	    true),
            CHECK(RC_FP_NOTE_NEAR_RACE_START_1, true),
            CHECK(RC_FP_NOTE_NEAR_RACE_START_2, true),
            CHECK(RC_FP_NOTE_NEAR_RACE_START_3, true),
            CHECK(RC_FP_NOTE_NEAR_RACE_START_4, true),
            CHECK(RC_FP_NOTE_SECOND_SLOPE_1,    true),
            CHECK(RC_FP_NOTE_SECOND_SLOPE_2,    true),
            CHECK(RC_FP_NOTE_SECOND_SLOPE_3,    true),
            CHECK(RC_FP_NOTE_SECOND_SLOPE_4,    true),
        },
        .connections = {
            CONNECTION(RR_FREEZEEZY_PEAK_INTERIOR_BOGGYS_IGLOO,         true),
            CONNECTION(RR_FREEZEEZY_PEAK_MAIN_LOWER,                    true),
            CONNECTION(RR_GRUNTILDAS_LAIR_NEAR_ENTRANCE_FREEZEEZY_PEAK, true),
        },
    };

    Regions[RR_FREEZEEZY_PEAK_INTERIOR_BOGGYS_IGLOO] = RandoRegion{ .regionName = "Boggy's Igloo", .mapId = MAP_41_FP_BOGGYS_IGLOO,
        .checks = {
            CHECK(RC_FP_MUMBO_TOKEN_INSIDE_BOGGYS_IGLOO,    true),
            CHECK(RC_FP_JIGGY_IGLOO,					    CAN_USE_ABILITY(ABILITY_10_TALON_TROT) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP) && CAN_USE_ABILITY(ABILITY_5_CLIMB)),
        },
        .connections = {
            CONNECTION(RR_FREEZEEZY_PEAK_ENTRANCE, true),
        },
    };

    Regions[RR_FREEZEEZY_PEAK_INTERIOR_MUMBOS_SKULL] = RandoRegion{ .regionName = "Inside Mumbo's Skull", .mapId = MAP_48_FP_MUMBOS_SKULL,
        .checks = {
            CHECK(RC_FP_JINJO_YELLOW,				  true),
            CHECK(RC_FP_NOTE_MUMBOS_SKULL_INTERIOR_1, true),
            CHECK(RC_FP_NOTE_MUMBOS_SKULL_INTERIOR_2, true),
            CHECK(RC_FP_NOTE_MUMBOS_SKULL_INTERIOR_3, true),
            CHECK(RC_FP_NOTE_MUMBOS_SKULL_INTERIOR_4, true),
            CHECK(RC_FP_NOTE_MUMBOS_SKULL_INTERIOR_5, true),
            CHECK(RC_FP_NOTE_MUMBOS_SKULL_INTERIOR_6, true),
        },
        .connections = {
            CONNECTION(RR_FREEZEEZY_PEAK_MAIN_LOWER, CAN_USE_ABILITY(ABILITY_E_WADING_BOOTS) || CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
        },
    };

    Regions[RR_FREEZEEZY_PEAK_INTERIOR_WOZZAS_CAVE] = RandoRegion{ .regionName = "Inside Wozza's Cave", .mapId = MAP_7F_FP_WOZZAS_CAVE,
        .checks = {
            CHECK(RC_FP_JINJO_ORANGE,				    CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
            CHECK(RC_FP_EMPTY_HONEYCOMB_WOZZAS_CAVE,    true),
            CHECK(RC_FP_SNS_ICE_KEY,				    CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP)),
        },
        .connections = {
            CONNECTION(RR_FREEZEEZY_PEAK_MAIN_LOWER, true),
        },
    };

    Regions[RR_FREEZEEZY_PEAK_MAIN_LOWER] = RandoRegion{ .regionName = "Lower Area near the Snowman", .mapId = MAP_27_FP_FREEZEEZY_PEAK,
        .checks = {
            CHECK(RC_FP_EMPTY_HONEYCOMB_UNDER_SIR_SLUSH,	    CAN_USE_ABILITY(ABILITY_1_BEAK_BOMB) && CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_JIGGY_BOGGY_RACE_1,					    CAN_USE_ABILITY(ABILITY_10_TALON_TROT) && CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
            CHECK(RC_FP_JIGGY_BOGGY_RACE_2,					    CAN_USE_ABILITY(ABILITY_10_TALON_TROT) && CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS) && CAN_USE_ABILITY(ABILITY_11_TURBO_TALON)),
            CHECK(RC_FP_JIGGY_SNOWMANS_BUTTONS,				    CAN_USE_ABILITY(ABILITY_1_BEAK_BOMB) && CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_JIGGY_WOZZA,						    CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
            CHECK(RC_FP_JINJO_GREEN,							true),
            CHECK(RC_FP_JINJO_PINK,							    CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP) || CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_MOLEHILL_BEAK_BOMB,				        true),
            CHECK(RC_FP_MUMBO_TOKEN_POTTED_TREE,                true),
            CHECK(RC_FP_MUMBO_TOKEN_PRESENT_STACK,              true),
            CHECK(RC_FP_MUMBO_TOKEN_SIR_SLUSH_NEAR_RACE_START,  CAN_USE_ABILITY(ABILITY_1_BEAK_BOMB) && CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_MUMBO_TOKEN_SIR_SLUSH_NEAR_RACE_FINISH, CAN_USE_ABILITY(ABILITY_1_BEAK_BOMB) && CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_MUMBO_TOKEN_SNOWMAN_LEFT_FOOT,          true),
            CHECK(RC_FP_MUMBO_TOKEN_SNOWMAN_RIGHT_FOOT,         true),
            CHECK(RC_FP_MUMBO_TOKEN_VILLAGE_CHIMNEY,            CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_MUMBO_TOKEN_WATER_BEHIND_SNOWMAN,       CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
            CHECK(RC_FP_NOTE_HOUSE_NEAR_MUMBO_1,			    true),
            CHECK(RC_FP_NOTE_HOUSE_NEAR_MUMBO_2,			    true),
            CHECK(RC_FP_NOTE_HOUSE_NEAR_MUMBO_3,			    true),
            CHECK(RC_FP_NOTE_HOUSE_NEAR_SIR_SLUSH_1,		    true),
            CHECK(RC_FP_NOTE_HOUSE_NEAR_SIR_SLUSH_2,		    true),
            CHECK(RC_FP_NOTE_HOUSE_NEAR_SIR_SLUSH_3,		    true),
            CHECK(RC_FP_NOTE_POND_AROUND_SIR_SLUSH_1,		    CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
            CHECK(RC_FP_NOTE_POND_AROUND_SIR_SLUSH_2,		    CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
            CHECK(RC_FP_NOTE_POND_AROUND_SIR_SLUSH_3,		    CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
            CHECK(RC_FP_NOTE_POND_AROUND_SIR_SLUCH_4,		    CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
            CHECK(RC_FP_NOTE_POND_AROUND_SIR_SLUSH_5,		    CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
            CHECK(RC_FP_NOTE_POND_AROUND_SIR_SLUSH_6,		    CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
            CHECK(RC_FP_NOTE_POND_AROUND_SIR_SLUSH_7,		    CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
            CHECK(RC_FP_NOTE_POND_AROUND_SIR_SLUSH_8,		    CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
            CHECK(RC_FP_NOTE_POND_AROUND_SIR_SLUSH_9,		    CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
            CHECK(RC_FP_NOTE_POTTED_TREE_1,					    true),
            CHECK(RC_FP_NOTE_POTTED_TREE_2,					    true),
            CHECK(RC_FP_NOTE_POTTED_TREE_3,					    true),
            CHECK(RC_FP_NOTE_POTTED_TREE_4,					    true),
            CHECK(RC_FP_NOTE_POTTED_TREE_5,					    true),
            CHECK(RC_FP_NOTE_PRESENTS_NEAR_FLIGHT_PAD_1,	    true),
            CHECK(RC_FP_NOTE_PRESENTS_NEAR_FLIGHT_PAD_2,	    true),
            CHECK(RC_FP_NOTE_PRESENTS_NEAR_FLIGHT_PAD_3,	    true),
            CHECK(RC_FP_NOTE_PRESENTS_NEAR_FLIGHT_PAD_4,	    true),
            CHECK(RC_FP_NOTE_SIR_SLUSH_NEAR_SNOWMAN_1,		    true),
            CHECK(RC_FP_NOTE_SIR_SLUSH_NEAR_SNOWMAN_2,		    true),
            CHECK(RC_FP_NOTE_SIR_SLUSH_NEAR_SNOWMAN_3,		    true),
            CHECK(RC_FP_NOTE_SIR_SLUSH_NEAR_SNOWMAN_4,		    true),
            CHECK(RC_FP_NOTE_SNOWMAN_LEFT_FOOT_1,			    true),
            CHECK(RC_FP_NOTE_SNOWMAN_LEFT_FOOT_2,			    true),
            CHECK(RC_FP_NOTE_SNOWMAN_LEFT_FOOT_3,			    true),
            CHECK(RC_FP_NOTE_SNOWMAN_LEFT_FOOT_4,			    true),
            CHECK(RC_FP_NOTE_SNOWMAN_LEFT_FOOT_5,			    true),
            CHECK(RC_FP_NOTE_SNOWMAN_RIGHT_FOOT_1,			    true),
            CHECK(RC_FP_NOTE_SNOWMAN_RIGHT_FOOT_2,			    true),
            CHECK(RC_FP_NOTE_SNOWMAN_RIGHT_FOOT_3,			    true),
            CHECK(RC_FP_NOTE_SNOWMAN_RIGHT_FOOT_4,			    true),
            CHECK(RC_FP_NOTE_SNOWMAN_RIGHT_FOOT_5,			    true),

        },
        .connections = {
            CONNECTION(RR_FREEZEEZY_PEAK_ENTRANCE, CAN_USE_ABILITY(ABILITY_10_TALON_TROT) || CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
            CONNECTION(RR_FREEZEEZY_PEAK_MAIN_UPPER, CAN_USE_ABILITY(ABILITY_10_TALON_TROT) || CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
            CONNECTION(RR_FREEZEEZY_PEAK_INTERIOR_MUMBOS_SKULL, CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CONNECTION(RR_FREEZEEZY_PEAK_POTTED_TREE, CAN_USE_ABILITY(ABILITY_5_CLIMB)),
            CONNECTION(RR_FREEZEEZY_PEAK_INTERIOR_WOZZAS_CAVE, CAN_USE_TRANSFORMATION(TRANSFORM_4_WALRUS)),
        },
        .events = {
            EVENT(RA_WITCH_SWITCH_FREEZEEZY_PEAK, CAN_USE_ABILITY(ABILITY_1_BEAK_BOMB) && CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER) && CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
        }
    };

    Regions[RR_FREEZEEZY_PEAK_MAIN_UPPER] = RandoRegion{ .regionName = "Upper Area near the Snowman", .mapId = MAP_27_FP_FREEZEEZY_PEAK,
        .checks = {
            CHECK(RC_FP_JIGGY_BEAT_ALL_SIR_SLUSH,   CAN_USE_ABILITY(ABILITY_1_BEAK_BOMB) && CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_JIGGY_SNOWMANS_PIPE,	    CAN_USE_ABILITY(ABILITY_10_TALON_TROT) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
            CHECK(RC_FP_JINJO_BLUE,				    CAN_EXTEND_JUMP_DISTANCE && CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
            CHECK(RC_FP_MUMBO_TOKEN_SLED_TO_BOGGY,  CAN_USE_ABILITY(ABILITY_10_TALON_TROT)),
            CHECK(RC_FP_NOTE_NEAR_WOZZA_1,		    true),
            CHECK(RC_FP_NOTE_NEAR_WOZZA_2,		    true),
            CHECK(RC_FP_NOTE_NEAR_WOZZA_3,		    true),
            CHECK(RC_FP_NOTE_NEAR_WOZZA_4,		    true),
            CHECK(RC_FP_NOTE_SNOWMAN_HAT_1,		    CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_NOTE_SNOWMAN_HAT_2,		    CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_NOTE_SNOWMAN_HAT_3,		    CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_NOTE_SNOWMAN_HAT_4,		    CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_NOTE_SNOWMAN_HAT_5,		    CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_NOTE_SNOWMAN_HAT_6,		    CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_NOTE_SNOWMAN_HAT_7,		    CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_NOTE_SNOWMAN_HAT_8,		    CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_1,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_2,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_3,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_4,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_5,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_6,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_7,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_8,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_9,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_10,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_11,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_12,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_13,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_14,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_15,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_16,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_17,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_18,	    true),
            CHECK(RC_FP_NOTE_SNOWMAN_SCARF_19,	    true),
        },
        .connections = {
            CONNECTION(RR_FREEZEEZY_PEAK_MAIN_LOWER, true),
        },
    };

    Regions[RR_FREEZEEZY_PEAK_POTTED_TREE] = RandoRegion{ .regionName = "Inside the Potted Tree", .mapId = MAP_53_FP_CHRISTMAS_TREE,
        .checks = {
            CHECK(RC_FP_JIGGY_INSIDE_THE_TREE,		    CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER) && CAN_USE_ABILITY(ABILITY_6_EGGS) && CAN_USE_ABILITY(ABILITY_9_FLIGHT)),
            CHECK(RC_FP_NOTE_POTTED_TREE_INTERIOR_1,    true),
            CHECK(RC_FP_NOTE_POTTED_TREE_INTERIOR_2,    true),
            CHECK(RC_FP_NOTE_POTTED_TREE_INTERIOR_3,    true),
            CHECK(RC_FP_NOTE_POTTED_TREE_INTERIOR_4,    true),
            CHECK(RC_FP_NOTE_POTTED_TREE_INTERIOR_5,    true),
            CHECK(RC_FP_NOTE_POTTED_TREE_INTERIOR_6,    true),
            CHECK(RC_FP_NOTE_POTTED_TREE_INTERIOR_7,    true),
            CHECK(RC_FP_NOTE_POTTED_TREE_INTERIOR_8,    true),
            CHECK(RC_FP_NOTE_POTTED_TREE_INTERIOR_9,    true),
            CHECK(RC_FP_NOTE_POTTED_TREE_INTERIOR_10,   true),
            CHECK(RC_FP_NOTE_POTTED_TREE_INTERIOR_11,   true),
            CHECK(RC_FP_NOTE_POTTED_TREE_INTERIOR_12,   true),
        },
        .connections = {
            CONNECTION(RR_FREEZEEZY_PEAK_MAIN_LOWER, true),
        },
    };

}, {});
// clang-format on